import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Next - Main",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
    <body
      suppressHydrationWarning
      className={'list-none bg-transparent'}
    >
      {children}
    </body>
</html>
  );
}